### ISSUE TITLE
Script crashes when evaluating merged discontinuous mentions

### ISSUE THREAD

**Issue by dnanhkhoa** [UCDenver-ccp/craft-shared-tasks#1]
Hi,

Thank you for creating this evaluation script.

Currently, I am using your script for evaluating coreference resolution share task. I have downloaded the latest version (v3.1.2_0) from DockerHub and do the evaluation on that. The context is that I was trying to read gold CoNLL files and write it down as predicted ones. I expected that it could obtain 100% F-score, but got an error like this:

```
craft@8f98280572df:~/evaluation$ boot eval-coreference
Classpath conflict: org.clojure/clojure version 1.8.0 already loaded, NOT loading version 1.10.1
Running coreference evaluation. Metric = muc
Running coreference evaluation. Metric = muc
Running coreference evaluation. Metric = bcub
Running coreference evaluation. Metric = bcub
Running coreference evaluation. Metric = ceafm
Running coreference evaluation. Metric = ceafm
Running coreference evaluation. Metric = ceafe
Running coreference evaluation. Metric = ceafe
Running coreference evaluation. Metric = blanc
Running coreference evaluation. Metric = blanc
Running coreference evaluation. Metric = lea
Running coreference evaluation. Metric = lea
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/muc.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/muc.allow_partial.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/lea.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/lea.allow_partial.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/bcub.allow_partial.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/bcub.log
Processing BLANC metric log file: /home/craft/evaluation/.intermediate-results/coref/blanc.allow_partial.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/ceafe.allow_partial.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/ceafm.log
Processing BLANC metric log file: /home/craft/evaluation/.intermediate-results/coref/blanc.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/ceafm.allow_partial.log
Processing coref metric log file: /home/craft/evaluation/.intermediate-results/coref/ceafe.log
                                    java.lang.Thread.run              Thread.java:  748
      java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
       java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
                     java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                                     ...                               
                     clojure.core/binding-conveyor-fn/fn                 core.clj: 1938
                                       boot.core/boot/fn                 core.clj: 1032
                                     boot.core/run-tasks                 core.clj: 1022
        boot.user$eval363$fn__364$fn__369$fn__370.invoke                         :   57
        boot.user$eval432$fn__433$fn__438$fn__439.invoke                         :   84 (repeats 12 times)
        boot.user$eval469$fn__470$fn__475$fn__476.invoke                         :  103
boot.user$eval469$fn__470$fn__475$fn__476$fn__477.invoke                         :  104
                craft-eval.coref/serialize-coref-results                coref.clj:  251
                                  clojure.core/reduce-kv                 core.clj: 6573
                             clojure.core.protocols/fn/G            protocols.clj:  174
                                         clojure.core/fn                 core.clj: 6547
                                     clojure.core/reduce                 core.clj: 6545
                             clojure.core.protocols/fn/G            protocols.clj:   13
                               clojure.core.protocols/fn            protocols.clj:   75
                      clojure.core.protocols/iter-reduce            protocols.clj:   49
                                      clojure.core/fn/fn                 core.clj: 6557
             craft-eval.coref/serialize-coref-results/fn                coref.clj:  263
                                                     ...                               
                                 clojure.core/merge-with                 core.clj: 2942
                                 clojure.core/merge-with                 core.clj: 2950
                                    clojure.core/reduce1                 core.clj:  915
                                    clojure.core/reduce1                 core.clj:  925
                          clojure.core/merge-with/merge2                 core.clj: 2957
                                    clojure.core/reduce1                 core.clj:  925
                     clojure.core/merge-with/merge-entry                 core.clj: 2954
                                          clojure.core/+                 core.clj:  973
                                                     ...                               
java.lang.NullPointerException: 
    clojure.lang.ExceptionInfo: 
    line: 409
craft@8f98280572df:~/evaluation$
```
Then, I have opened all logs reported on the screen to see what happened and found that some of metrics, for example BCUB, show #TP counts as **a decimal number** like log below, maybe, this number violates your regex patterns to extract the score from log:

```
====== TOTALS =======
Identification of Mentions: Recall: (1853 / 1854) 99.94%	Precision: (1853 / 1853) 100%	F1: 99.97%
--------------------------------------------------------------------------
Coreference: Recall: (1852.33333333333 / 1854) 99.91%	Precision: (1853 / 1853) 100%	F1: 99.95%
--------------------------------------------------------------------------
------------------ end /home/craft/eval-data/coreference/conllcoref/16628246.conll
```

I'm not sure but in my reading/writing CoNLL code, I do an additional step, namely, I correct (merge) continuous mentions annotated as discontinuous mentions.

For example:

Gold data:
File: 17069463.conll
Line: 4931
ID: 266a

```
1626108	0	5	inbred	JJ	-	-	-	-	-	-	-	(266a
1626108	0	6	RanBP2	NN	-	-	-	-	-	-	-	-
1626108	0	7	+	SYM	-	-	-	-	-	-	-	-
1626108	0	8	/	HYPH	-	-	-	-	-	-	-	-
1626108	0	9	−	SYM	-	-	-	-	-	-	-	-
1626108	0	10	mice	NNS	-	-	-	-	-	-	-	-
1626108	0	11	on	IN	-	-	-	-	-	-	-	-
1626108	0	12	high	JJ	-	-	-	-	-	-	-	(267
1626108	0	13	-	HYPH	-	-	-	-	-	-	-	-
1626108	0	14	fat	NN	-	-	-	-	-	-	-	-
1626108	0	15	(	-LRB-	-	-	-	-	-	-	-	-
1626108	0	16	~	SYM	-	-	-	-	-	-	-	(268
1626108	0	17	10	CD	-	-	-	-	-	-	-	-
1626108	0	18	%	NN	-	-	-	-	-	-	-	-
1626108	0	19	fat	NN	-	-	-	-	-	-	-	268)
1626108	0	20	)	-RRB-	-	-	-	-	-	-	-	-
1626108	0	21	diet	NN	-	-	-	-	-	-	-	(266a)|267)|266a)
```

Obviously, mention at word 21 **(266a)** is a substring of a mention from word 5 **(266a** to word 21 **266a)**. I understand that there is **only one discontinuous mention** with offset from [(5, 21), (21, 21)]. That's it.

In my predicted data, I normalized as follows:

```
1626108	0	5	inbred	JJ	-	-	-	-	-	-	-	(248
1626108	0	6	RanBP2	NN	-	-	-	-	-	-	-	-
1626108	0	7	+	SYM	-	-	-	-	-	-	-	-
1626108	0	8	/	HYPH	-	-	-	-	-	-	-	-
1626108	0	9	−	SYM	-	-	-	-	-	-	-	-
1626108	0	10	mice	NNS	-	-	-	-	-	-	-	-
1626108	0	11	on	IN	-	-	-	-	-	-	-	-
1626108	0	12	high	JJ	-	-	-	-	-	-	-	(244
1626108	0	13	-	HYPH	-	-	-	-	-	-	-	-
1626108	0	14	fat	NN	-	-	-	-	-	-	-	-
1626108	0	15	(	-LRB-	-	-	-	-	-	-	-	-
1626108	0	16	~	SYM	-	-	-	-	-	-	-	(243
1626108	0	17	10	CD	-	-	-	-	-	-	-	-
1626108	0	18	%	NN	-	-	-	-	-	-	-	-
1626108	0	19	fat	NN	-	-	-	-	-	-	-	243)
1626108	0	20	)	-RRB-	-	-	-	-	-	-	-	-
1626108	0	21	diet	NN	-	-	-	-	-	-	-	244)|248)
```

Can see that there is only mention from word 5 to word 21 too **(248)** corresponding to (266a) above.

I have just applied this additional step for discontinuous mentions only. But according to the definition for discontinuous mentions, I think that in this case, predicting a mention with offset (5, 21) must be the same with [(5, 21), (21, 21)] above. Is it right?

And after doing statistics, I found that there are 2 files causing this error. 16628246.conll **391a** and 17069463.conll **(266a)** (I have also attached these files here) [error.zip](https://github.com/UCDenver-ccp/craft-shared-tasks/files/3333029/error.zip).

I think we should fix this issue because we don't know how to predict "enough spans" for a mention to avoid crashing evaluation script. I mean we can treat the above example as a wrong prediction but the script must run without any error.

Thank you in advance,

Khoa

**Comment by bill-baumgartner** [comment]
Dear Khoa,
Thank you for your very complete error report. I will look into this and get back to you with a fix.
Best,
Bill

**Comment by bill-baumgartner** [comment]
Dear Khoa,

Thank you again for pointing out this issue. I was able to reproduce the error thanks to your very detailed issue report. As you observed, the issue is a results of some improperly formatted discontinuous spans. They are a result of errors in the original coreference annotation. I have updated the evaluation code to address this issue. There is now a validation step at the beginning of the coreference evaluation process that will check both the gold standard and test files for proper discontinuous spans. 

Discontinuous spans are validated in two ways. First, if a discontinuous span contains adjacent component spans, e.g. [35..43][44..52], or component spans are are separated by only whitespace, then the component spans are combined, e.g. [35..52]. Second, if the discontinuous span contains a component span that is nested in another component span, e.g. [78..92][88..92], then the nested span is removed, e.g. [78..92].

While fixing issues with the discontinuous spans, I was also able to address an issue whereby annotations of type "nonreferential pronoun" were being output as part of the CoNLL-Coref file format. These annotation types should not have been included, and are now excluded from the output.

I've released an update to the CRAFT corpus that includes the fix to address the issue you reported. Please update to `CRAFT v3.1.3`, and to the `0.1.2` version of this project. Or, if you are running the evaluations via Docker, please use the `ucdenverccp/craft-eval:3.1.3_0.1.2` container which is now available on [DockerHub](https://cloud.docker.com/u/ucdenverccp/repository/docker/ucdenverccp/craft-eval/tags).

Let me know if you continue to experience this issue, or if you have further questions.

Best,
Bill

**Comment by dnanhkhoa** [comment]
Dear Bill,

Thank you so much for your time and effort to fix this issue. I will rerun our model on the latest evaluation script and will let you know if there is any problem. Thank you.

Best regards,
Khoa

**Comment by dnanhkhoa** [comment]
Now, the latest version works perfectly. Thanks.
